[build]
  publish = "."
  command = "echo 'Static site with Netlify functions'"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/tts"
  to = "/.netlify/functions/tts-azure"
  status = 200

[build.environment]
  NODE_VERSION = "18"